config/routes.rb
Rails.application.routes.draw do
  resources :cart_themes
  resources :video_themes
  resources :sliders
  resources :product_images
  resources :products
  resources :subcategories
  resources :categories
  devise_for :customers
  devise_for :vendors
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/cart_theme.rb
class CartTheme < ApplicationRecord
end

app/controllers/cart_themes_controller.rb
class CartThemesController < ApplicationController
  before_action :set_cart_theme, only: %i[ show edit update destroy ]

  # GET /cart_themes or /cart_themes.json
  def index
    @cart_themes = CartTheme.all
  end

  # GET /cart_themes/1 or /cart_themes/1.json
  def show
  end

  # GET /cart_themes/new
  def new
    @cart_theme = CartTheme.new
  end

  # GET /cart_themes/1/edit
  def edit
  end

  # POST /cart_themes or /cart_themes.json
  def create
    @cart_theme = CartTheme.new(cart_theme_params)

    respond_to do |format|
      if @cart_theme.save
        format.html { redirect_to cart_theme_url(@cart_theme), notice: "Cart theme was successfully created." }
        format.json { render :show, status: :created, location: @cart_theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_themes/1 or /cart_themes/1.json
  def update
    respond_to do |format|
      if @cart_theme.update(cart_theme_params)
        format.html { redirect_to cart_theme_url(@cart_theme), notice: "Cart theme was successfully updated." }
        format.json { render :show, status: :ok, location: @cart_theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_themes/1 or /cart_themes/1.json
  def destroy
    @cart_theme.destroy

    respond_to do |format|
      format.html { redirect_to cart_themes_url, notice: "Cart theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_theme
      @cart_theme = CartTheme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_theme_params
      params.require(:cart_theme).permit(:theme, :status)
    end
end

app/helpers/cart_themes_helper.rb
module CartThemesHelper
end

app/views/cart_themes/_cart_theme.html.erb
<div id="<%= dom_id cart_theme %>">
  <p>
    <strong>Theme:</strong>
    <%= cart_theme.theme %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= cart_theme.status %>
  </p>

</div>

app/views/cart_themes/_form.html.erb
<%= form_with(model: cart_theme) do |form| %>
  <% if cart_theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart_theme.errors.count, "error") %> prohibited this cart_theme from being saved:</h2>

      <ul>
        <% cart_theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :theme, style: "display: block" %>
    <%= form.text_field :theme %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_themes/edit.html.erb
<h1>Editing cart theme</h1>

<%= render "form", cart_theme: @cart_theme %>

<br>

<div>
  <%= link_to "Show this cart theme", @cart_theme %> |
  <%= link_to "Back to cart themes", cart_themes_path %>
</div>

app/views/cart_themes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cart themes</h1>

<div id="cart_themes">
  <% @cart_themes.each do |cart_theme| %>
    <%= render cart_theme %>
    <p>
      <%= link_to "Show this cart theme", cart_theme %>
    </p>
  <% end %>
</div>

<%= link_to "New cart theme", new_cart_theme_path %>

app/views/cart_themes/new.html.erb
<h1>New cart theme</h1>

<%= render "form", cart_theme: @cart_theme %>

<br>

<div>
  <%= link_to "Back to cart themes", cart_themes_path %>
</div>

app/views/cart_themes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart_theme %>

<div>
  <%= link_to "Edit this cart theme", edit_cart_theme_path(@cart_theme) %> |
  <%= link_to "Back to cart themes", cart_themes_path %>

  <%= button_to "Destroy this cart theme", @cart_theme, method: :delete %>
</div>