config/routes.rb
Rails.application.routes.draw do
  resources :cart_themes
  resources :video_themes
  resources :sliders
  resources :product_images
  resources :products
  resources :subcategories
  resources :categories
  devise_for :customers
  devise_for :vendors
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  belongs_to :vendor
  mount_uploader :image, ImageUploader
end

app/controllers/product_images_controller.rb
class ProductImagesController < ApplicationController
  before_action :set_product_image, only: %i[ show edit update destroy ]

  # GET /product_images or /product_images.json
  def index
    @product_images = ProductImage.all
  end

  # GET /product_images/1 or /product_images/1.json
  def show
  end

  # GET /product_images/new
  def new
    @product_image = ProductImage.new
  end

  # GET /product_images/1/edit
  def edit
  end

  # POST /product_images or /product_images.json
  def create
    @product_image = ProductImage.new(product_image_params)

    respond_to do |format|
      if @product_image.save
        format.html { redirect_to product_image_url(@product_image), notice: "Product image was successfully created." }
        format.json { render :show, status: :created, location: @product_image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_images/1 or /product_images/1.json
  def update
    respond_to do |format|
      if @product_image.update(product_image_params)
        format.html { redirect_to product_image_url(@product_image), notice: "Product image was successfully updated." }
        format.json { render :show, status: :ok, location: @product_image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_images/1 or /product_images/1.json
  def destroy
    @product_image.destroy

    respond_to do |format|
      format.html { redirect_to product_images_url, notice: "Product image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_image
      @product_image = ProductImage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_image_params
      params.require(:product_image).permit(:name, :image, :status, :product_id, :vendor_id)
    end
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/views/product_images/_form.html.erb
<%= form_with(model: product_image) do |form| %>
  <% if product_image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_image.errors.count, "error") %> prohibited this product_image from being saved:</h2>

      <ul>
        <% product_image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :vendor_id, style: "display: block" %>
    <%= form.text_field :vendor_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_images/_product_image.html.erb
<div id="<%= dom_id product_image %>">
  <p>
    <strong>Name:</strong>
    <%= product_image.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= product_image.image %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= product_image.status %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= product_image.product_id %>
  </p>

  <p>
    <strong>Vendor:</strong>
    <%= product_image.vendor_id %>
  </p>

</div>

app/views/product_images/edit.html.erb
<h1>Editing product image</h1>

<%= render "form", product_image: @product_image %>

<br>

<div>
  <%= link_to "Show this product image", @product_image %> |
  <%= link_to "Back to product images", product_images_path %>
</div>

app/views/product_images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product images</h1>

<div id="product_images">
  <% @product_images.each do |product_image| %>
    <%= render product_image %>
    <p>
      <%= link_to "Show this product image", product_image %>
    </p>
  <% end %>
</div>

<%= link_to "New product image", new_product_image_path %>

app/views/product_images/new.html.erb
<h1>New product image</h1>

<%= render "form", product_image: @product_image %>

<br>

<div>
  <%= link_to "Back to product images", product_images_path %>
</div>

app/views/product_images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_image %>

<div>
  <%= link_to "Edit this product image", edit_product_image_path(@product_image) %> |
  <%= link_to "Back to product images", product_images_path %>

  <%= button_to "Destroy this product image", @product_image, method: :delete %>
</div>