config/routes.rb
Rails.application.routes.draw do
  resources :cart_themes
  resources :video_themes
  resources :sliders
  resources :product_images
  resources :products
  resources :subcategories
  resources :categories
  devise_for :customers
  devise_for :vendors
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_theme.rb
class CartTheme < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	mount_uploader :image, ImageUploader

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
  belongs_to :vendor
  mount_uploader :image, ImageUploader

end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  belongs_to :vendor
  mount_uploader :image, ImageUploader
end

app/models/slider.rb
class Slider < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video_theme.rb
class VideoTheme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :status, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :quantity, :image, :status, :category_id, :subcategory_id, :vendor_id)
    end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  before_action :set_slider, only: %i[ show edit update destroy ]

  # GET /sliders or /sliders.json
  def index
    @sliders = Slider.all
  end

  # GET /sliders/1 or /sliders/1.json
  def show
  end

  # GET /sliders/new
  def new
    @slider = Slider.new
  end

  # GET /sliders/1/edit
  def edit
  end

  # POST /sliders or /sliders.json
  def create
    @slider = Slider.new(slider_params)

    respond_to do |format|
      if @slider.save
        format.html { redirect_to slider_url(@slider), notice: "Slider was successfully created." }
        format.json { render :show, status: :created, location: @slider }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sliders/1 or /sliders/1.json
  def update
    respond_to do |format|
      if @slider.update(slider_params)
        format.html { redirect_to slider_url(@slider), notice: "Slider was successfully updated." }
        format.json { render :show, status: :ok, location: @slider }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sliders/1 or /sliders/1.json
  def destroy
    @slider.destroy

    respond_to do |format|
      format.html { redirect_to sliders_url, notice: "Slider was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Slider.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def slider_params
      params.require(:slider).permit(:name, :image, :status, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_themes_helper.rb
module CartThemesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/video_themes_helper.rb
module VideoThemesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= category.status %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= category.image %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :subcategory_id, style: "display: block" %>
    <%= form.text_field :subcategory_id %>
  </div>

  <div>
    <%= form.label :vendor_id, style: "display: block" %>
    <%= form.text_field :vendor_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= product.quantity %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= product.image %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= product.status %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

  <p>
    <strong>Subcategory:</strong>
    <%= product.subcategory_id %>
  </p>

  <p>
    <strong>Vendor:</strong>
    <%= product.vendor_id %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/sliders/_form.html.erb
<%= form_with(model: slider) do |form| %>
  <% if slider.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(slider.errors.count, "error") %> prohibited this slider from being saved:</h2>

      <ul>
        <% slider.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sliders/_slider.html.erb
<div id="<%= dom_id slider %>">
  <p>
    <strong>Name:</strong>
    <%= slider.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= slider.image %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= slider.status %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= slider.category_id %>
  </p>

</div>

app/views/sliders/edit.html.erb
<h1>Editing slider</h1>

<%= render "form", slider: @slider %>

<br>

<div>
  <%= link_to "Show this slider", @slider %> |
  <%= link_to "Back to sliders", sliders_path %>
</div>

app/views/sliders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sliders</h1>

<div id="sliders">
  <% @sliders.each do |slider| %>
    <%= render slider %>
    <p>
      <%= link_to "Show this slider", slider %>
    </p>
  <% end %>
</div>

<%= link_to "New slider", new_slider_path %>

app/views/sliders/new.html.erb
<h1>New slider</h1>

<%= render "form", slider: @slider %>

<br>

<div>
  <%= link_to "Back to sliders", sliders_path %>
</div>

app/views/sliders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @slider %>

<div>
  <%= link_to "Edit this slider", edit_slider_path(@slider) %> |
  <%= link_to "Back to sliders", sliders_path %>

  <%= button_to "Destroy this slider", @slider, method: :delete %>
</div>